#ifndef LUAINTERFACE_GLOBAL_H
#define LUAINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LUAINTERFACE_LIBRARY)
#  define LUAINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LUAINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LUAINTERFACE_GLOBAL_H
